### ISSUE TITLE
New Update Unable to play in server

### ISSUE THREAD

**Issue by rainysux** [Kitisplode/minecraftMod-golemFirstStone#9]
https://pastebin.com/9cp2H5Bv
It works fine in single player 1.20.1

**Comment by Kitisplode** [comment]
i'll look into this, thanks

**Comment by rainysux** [comment]
I am using connector (fabric to forge mods) so dont be phased about fabric mods on forge launcher. It works perfectly fine when I backport it from last weeks update.

**Comment by Kitisplode** [comment]
i think i've fixed this issue in the latest forge release, hopefully

**Comment by rainysux** [comment]
it works now thank you for your hard work :)
